/**
 * Represents a moderation case that tracks the lifecycle of an anti-cheat alert
 * from detection through resolution. Each case maintains an audit trail of all
 * moderator actions and decisions.
 *
 * @interface ModerationCase
 */
export interface ModerationCase {
  /**
   * Unique identifier for this moderation case
   * Generated by the backend when the case is created
   * Format: typically "CASE-{timestamp}-{sequence}" or UUID
   */
  caseId: string;

  /**
   * The player ID associated with this case
   * Links back to the AntiCheatEvent.playerId
   */
  playerId: string;

  /**
   * Discord user ID of the moderator who performed this action
   * Used for audit trails and permission checking
   */
  moderatorId: string;

  /**
   * The moderation action taken on this case
   * - "FLAG": Mark player for monitoring/follow-up
   * - "BAN": Permanent or temporary ban (requires senior approval)
   * - "REQUEST_EVIDENCE": Request additional evidence from anti-cheat system
   * - "RESOLVE": Close case as resolved/dismissed
   */
  action: ModerationAction;

  /**
   * Optional reason provided by the moderator for their decision
   * Required for ban actions, optional for others
   * Should be descriptive enough for audit purposes
   */
  reason?: string;

  /**
   * ISO 8601 timestamp when this moderation action was taken
   * Used for chronological ordering and audit logs
   */
  createdAt: string;
}

/**
 * Enumeration of possible moderation actions that can be taken on a case
 */
export type ModerationAction = "FLAG" | "BAN" | "REQUEST_EVIDENCE" | "RESOLVE";
